tcase: (improved) tcase can now accept either a C++ file or an executable.

diff --git a/bin/tcase b/bin/tcase
--- a/bin/tcase
+++ b/bin/tcase
@@ -1,20 +1,30 @@
-#!/bin/bash
+#!/bin/zsh
 
+red=`tput setaf 1`
 blue=`tput setaf 4`
 green=`tput setaf 2`
 reset=`tput sgr0`
 
-# compile the C++ source file
-makecp $*
-if [ ! $? -eq 0 ]; then
+filepath="$(dirname "$1")"
+if [[ -f $1 ]]; then
+	if [[ -x $1 ]]; then
+		filename=$(basename -- "$1") # get file name without the path
+	elif [[ `echo $1 | rg '.cpp$'` ]] || [[ `echo $1 | rg '.C$'` ]] || [[ `echo $1 | rg '.cc$'` ]] || [[ `echo $1 | rg '.CPP$'` ]] || [[ `echo $1 | rg '.c++$'` ]] || [[ `echo $1 | rg '.cp$'` ]] || [[ `echo $1 | rg '.cxx$'` ]]; then
+		makecp $1
+		[[ $? -ne 0 ]] && exit 1
+
+		filename=$(basename -- "$1") # get file name without the path
+		filename="${filename%.*}"  # file name without the extension
+		filepath="."
+	else 
+		echo "${red}ERROR:${reset} Neither a C++ file nor an executable!"
+		exit 1
+	fi
+else
+	echo "${red}ERROR:${reset} File doesn't exist!"
 	exit 1
 fi
 
-filename=$(basename -- "$*") # get file name without the path
-extension="${filename##*.}"
-filename="${filename%.*}"  # file name without the extension
-
-# run test cases
 
 testcase=1
 while [ -f in$testcase ]; do 
@@ -32,11 +42,10 @@ while [ -f in$testcase ]; do
 		echo "${blue}~~~~~ TEST-CASE:-$testcase ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${reset}"
 	fi
 
-	./$filename < in$testcase
-	if [ ! $? -eq 0 ]
+	$filepath/$filename < in$testcase
+	if [ $? -ne 0 ]
 	then
 		break
 	fi
 	testcase=$(($testcase+1))
 done
-
